/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_xcm_demo_jni_JniMethod */

#ifndef _Included_com_example_xcm_demo_jni_JniMethod
#define _Included_com_example_xcm_demo_jni_JniMethod
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_xcm_demo_jni_JniMethod
 * Method:    getNativeString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_xcm_demo_jni_JniMethod_getNativeString
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
